### ISSUE TITLE
Constructor in chain.json

### ISSUE THREAD

**Issue by cyberbono3** [miguelmota/solidity-create2-example#2]
Hey. I have a question to you. 
According to [parity wiki](https://wiki.parity.io/Chain-specification) ,
"The constructor bytecode is executed when the genesis is created and the code returned by the “constructor” is stored in the genesis state."
Why you use it [here](https://github.com/miguelmota/solidity-create2-example/blob/master/chain.json#L53) ?

**Comment by miguelmota** [comment]
It's an artifact from using the same chain config from a different project. It's been removed.
